// Curated icon set for Feature Grid / Trust Badge blocks — a merchant picks
// a name from a dropdown, never writes an SVG or class name themselves.
import {
  Award,
  BadgeCheck,
  BadgeDollarSign,
  BadgePercent,
  Banknote,
  Boxes,
  CalendarCheck,
  CheckCircle2,
  ClipboardCheck,
  Clock,
  Coins,
  CreditCard,
  Crown,
  Fingerprint,
  FileCheck2,
  Flame,
  Gem,
  Gift,
  Globe,
  HandCoins,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  Infinity,
  KeyRound,
  Leaf,
  LifeBuoy,
  Lock,
  Mail,
  MapPin,
  Medal,
  MessageCircle,
  Package,
  PackageCheck,
  Percent,
  Phone,
  PiggyBank,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Ship,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Store,
  Target,
  ThumbsUp,
  Timer,
  Trophy,
  TrendingUp,
  Truck,
  Umbrella,
  UserCheck,
  Users,
  CircleCheckBig,
  Warehouse,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const BLOCK_ICON_MAP: Record<string, LucideIcon> = {
  award: Award,
  "badge-check": BadgeCheck,
  "badge-dollar": BadgeDollarSign,
  "badge-percent": BadgePercent,
  cash: Banknote,
  boxes: Boxes,
  "calendar-check": CalendarCheck,
  "check-circle": CheckCircle2,
  "clipboard-check": ClipboardCheck,
  clock: Clock,
  coins: Coins,
  "credit-card": CreditCard,
  crown: Crown,
  fingerprint: Fingerprint,
  "file-check": FileCheck2,
  flame: Flame,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  "hand-coins": HandCoins,
  handshake: Handshake,
  headphones: Headphones,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  infinity: Infinity,
  key: KeyRound,
  leaf: Leaf,
  "life-buoy": LifeBuoy,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  medal: Medal,
  "message-circle": MessageCircle,
  package: Package,
  "package-check": PackageCheck,
  percent: Percent,
  phone: Phone,
  "piggy-bank": PiggyBank,
  recycle: Recycle,
  refresh: RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  return: RotateCcw,
  ship: Ship,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  target: Target,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  "trending-up": TrendingUp,
  trophy: Trophy,
  truck: Truck,
  umbrella: Umbrella,
  "user-check": UserCheck,
  users: Users,
  verified: CircleCheckBig,
  warehouse: Warehouse,
  wallet: Wallet,
  wrench: Wrench,
  zap: Zap,
};

export const BLOCK_ICON_NAMES = Object.keys(BLOCK_ICON_MAP);

export function resolveBlockIcon(name: string | null | undefined): LucideIcon {
  return BLOCK_ICON_MAP[name ?? ""] ?? Star;
}
